// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Use DIRECT_URL for db push / migrate — PgBouncer (pooler) does not support all DDL.
  // App runtime still uses DATABASE_URL via src/lib/prisma.js
  datasource: {
    url: env("DIRECT_URL"),
  },
});
